import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


// line height 82.%

const inter = Inter({
  weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'/ShortLogo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`w-full h-full ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
